\c postgres
DROP DATABASE TEMP_DB_NAME;

CREATE DATABASE TEMP_DB_NAME WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.UTF-8';
GRANT ALL PRIVILEGES ON DATABASE TEMP_DB_NAME TO TEMP_DB_USER;
ALTER DATABASE TEMP_DB_NAME OWNER TO TEMP_DB_USER;

\connect TEMP_DB_NAME
